const productores = {
"BV-D1-001": {nombre: "MARINA  CHORÉ ZEBALLOS", ci: "6253862", Asociación: "SANTA BÁRBARA DE LOS MANZANOS", estado: "Afiliado válido"},
"BV-D1-002": {nombre: "MARIA CRISTINA DAZA MOSTAZEDA", ci: "3911789", Asociación: "SANTA BÁRBARA DE LOS MANZANOS", estado: "Afiliado válido"},
  
"BV-D2-001": {nombre: "LORGIO JUSTINIANO CAMARGO", ci: "3174924", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-002": {nombre: "GONZALO RODRIGUEZ DIAS", ci: "4686826", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-003": {nombre: "AVELINO RODRIGUEZ MENDIETA", ci: "3770486", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-004": {nombre: "JUAN WALTER IBAÑEZ CARI", ci: "2972612", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-005": {nombre: "NELSON RUDI IBAÑEZ VOCAL ", ci: "9806259", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-006": {nombre: "JESUS FERNANDEZ FLORES", ci: "4590284", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-007": {nombre: "FRANZ REYNALDO CALA", ci: "8187156", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-008": {nombre: "SIXTO LLAVE FRANCO", ci: "8163857", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-009": {nombre: "PONCIANO SANDOVAL MORALES", ci: "6293239", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-010": {nombre: "TOMAS CALIZAYA MENDOZA", ci: "3224289", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-011": {nombre: "DOMINGO BARRIOS VILLARPANDO", ci: "7827564", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-012": {nombre: "FELIX YAPO MAMANI", ci: "2972594", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-013": {nombre: "BENJAMIN LOAYZA CALIZAYA", ci: "17770710", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-014": {nombre: "JOSE ARIEL SILES ORTEGA", ci: "5828754", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-015": {nombre: "CELESTINO  HUAYNOCA TOLA", ci: "3749445", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-016": {nombre: "ESTHER FAJARDO CRUZ", ci: "3936858", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-017": {nombre: "ANTONIO BASCOPE HIDALGO", ci: "2900692", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-018": {nombre: "FORTUNATO SANDOVAL ", ci: "2972762", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-019": {nombre: "MANUEL MONTERO TOMICHA", ci: "2955692", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-020": {nombre: "JULIANA MENESES SACACA", ci: "9696142", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-021": {nombre: "ERLINDA ZURITA CESPEDEZ", ci: "4648791", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-022": {nombre: "WILSON MEJIA HERRERA", ci: "5394954", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-023": {nombre: "SANTUSA SANDOVAL FRANCO", ci: "9711545", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-024": {nombre: "LICET CARDENAS DOMINGUEZ", ci: "6287779", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-025": {nombre: "JAVIER DAVID MAMANI AUZA", ci: "5829664", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-026": {nombre: "BENITA CALIZAYA FAJARDO", ci: "3224290", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-027": {nombre: "MARTHA VACA BECERRA", ci: "4548930", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-028": {nombre: "MERCEDES PERALTA DE HUAYNOCA ", ci: "3749446", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-029": {nombre: "ANA MARIA YAPU ROBLES", ci: "3190809", Asociación: "HUAYTÚ", estado: "Afiliado válido"},
"BV-D2-030": {nombre: "TEODORO AGUILAR ", ci: "", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-031": {nombre: "FEDERICO PUMA ", ci: "", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-032": {nombre: "CRISPIN  CHOQUE ", ci: "", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-033": {nombre: "RAUL JAILLITA ", ci: "4629935", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-034": {nombre: "ANTONIO CONDORI ", ci: "4678664", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-035": {nombre: "REINALDO CONDORI ", ci: "8970314", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-036": {nombre: "GREGORIO NINA ", ci: "5420844", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-037": {nombre: "MARCIAL COLQUE ", ci: "6478665", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-038": {nombre: "EMILIO  FLORES ", ci: "1368032", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-039": {nombre: "LUCIO  RAMIREZ ", ci: "10514216", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-040": {nombre: "ESTEBAN PUMA ", ci: "3238650", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-041": {nombre: "ROLI PUMA ", ci: "9765396", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-042": {nombre: "ROBERTO LUCAS ", ci: "6321189", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-043": {nombre: "ERNESTO MAMANI ", ci: "", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-044": {nombre: "ENRIQUE GONZALES ", ci: "3577235", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-045": {nombre: "DEISI  GERÓNIMO ", ci: "9046212", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-046": {nombre: "GERMÁN PUMA TOCO", ci: "8954452", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-047": {nombre: "WALBERTO PUMA ", ci: "7809972", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-048": {nombre: "MARIO JESÚS ", ci: "6384063", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-049": {nombre: "MARCO PUMA ", ci: "11392707", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-050": {nombre: "ELIAS HUGARTRE ", ci: "9805403", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-051": {nombre: "FELIX CHOQUE ", ci: "8945878", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-052": {nombre: "ERMINIA CARDENAS ", ci: "9797048", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-053": {nombre: "NICOLAS SUBIA ", ci: "3197142", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-054": {nombre: "GREGORIO FLORES ", ci: "7803768", Asociación: "POZA AZUL", estado: "Afiliado válido"},
"BV-D2-055": {nombre: "NICOLASA ALANIS ", ci: "4637754", Asociación: "POZA AZUL", estado: "Afiliado válido"},

  
"BV-D5-001": {nombre: "EDITH HERRERA DE VARGAS ", ci: "1593770", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-002": {nombre: "JULIO EFRAIN JEREZ CRUZ", ci: "13107180", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-003": {nombre: "INGRID MOLE COIMBRA", ci: "10805090", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-004": {nombre: "EDITHA RODRIGUEZ DAZA", ci: "5836996", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-005": {nombre: "MAURICIO PUTARÉ CUASASE", ci: "16878742", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-006": {nombre: "GEERT HANS TIEMEN HOEKSTRA", ci: "E-0027255", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-007": {nombre: "TITO SANDOVAL GUZMAN ", ci: "2857060", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-008": {nombre: "CRISOSTOMO  AVILA CARVAJAL", ci: "1940217", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-009": {nombre: "ISAAC SALVATIERRA MONTENEGRO", ci: "1952280", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-010": {nombre: "JORGE GALLARDO RODRIGUEZ", ci: "4551589-1C", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-011": {nombre: "CONSTANSA SOSA ", ci: "3267094", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-012": {nombre: "SANTOS PARADA RIVERO", ci: "8210790", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-013": {nombre: "ARTURO  VARGAS ARAUZ", ci: "5856242", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-014": {nombre: "GIL ANTONIO SALVATIERRA MONTENEGRO", ci: "1996915", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-015": {nombre: "ESTANISLAO HUGO SOSA URRUTIA", ci: "4698973-1I", Asociación: "ARBOLEDA", estado: "Afiliado válido"},
"BV-D5-016": {nombre: "JUANA MAMANI DE ASILLO ", ci: "2969353", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-017": {nombre: "YENNY CONTRERAS MACEDO", ci: "7787586", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-018": {nombre: "JAIME SOTILLO FLORES", ci: "7746876", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-019": {nombre: "DANIEL SOTILLO ISLA", ci: "9054196", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-020": {nombre: "PEDRO SOTILLO IRAÑA", ci: "1947935", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-021": {nombre: "GLADY ONOFRE ROMAN", ci: "8244470", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-022": {nombre: "ZENOBIA MACEDO ", ci: "3423409", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-023": {nombre: "JULIAN PUCHO YUCRA", ci: "4088205", Asociación: "EL PALMAR", estado: "Afiliado válido"},
"BV-D5-024": {nombre: "MIGUEL ANGEL AVILA VACA", ci: "7803605", Asociación: "SAN MIGUELITO", estado: "Afiliado válido"},
"BV-D5-025": {nombre: "VILMA VACA ZEBALLOS", ci: "9051453", Asociación: "SAN MIGUELITO", estado: "Afiliado válido"},
"BV-D5-026": {nombre: "EDWIN MANUEL GAMARRA PEÑAFIEL", ci: "3218764", Asociación: "PALACIOS", estado: "Afiliado válido"},
"BV-D5-027": {nombre: "NELSON  LORA ARAMAYO", ci: "6361788", Asociación: "PALACIOS", estado: "Afiliado válido"},
"BV-D5-028": {nombre: "FAVIANA COSSIO VARGAS", ci: "6529222", Asociación: "PALACIOS", estado: "Afiliado válido"},
"BV-D5-029": {nombre: "MARCO ANTONIO OLIVA GUTIERREZ", ci: "7803622", Asociación: "PALACIOS", estado: "Afiliado válido"},
"BV-D5-030": {nombre: "HORMANDO OLIVA GUTIERREZ", ci: "7803639", Asociación: "PALACIOS", estado: "Afiliado válido"},

  
"BV-D6-001": {nombre: "TEODORO OLIVERA APAZA", ci: "2986416", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-002": {nombre: "VICTOR SALVADOR LOPEZ", ci: "2744085", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-003": {nombre: "EUFRACIO QUISPE PEREZ", ci: "4258853", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-004": {nombre: "GUILLERMO SEJAS OCHALI", ci: "7690471", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-005": {nombre: "GRETA ALIVERA SEJAS", ci: "7803696", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-006": {nombre: "ELISEO ZURITA FLORES", ci: "7711670", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-007": {nombre: "EMETERIO SEJAS ROCHA", ci: "5419120", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-008": {nombre: "LICEO  AMURRIO  COCA", ci: "9004092", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-009": {nombre: "MARTIN MARTINEZ ACUÑA", ci: "4647607", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-010": {nombre: "FABIAN SEJAS  GUTIERREZ", ci: "9685740", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-011": {nombre: "JHONNY GALEAN VARGAS", ci: "5838652", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-012": {nombre: "ABELINO  LUNA  FLORES", ci: "4484792", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-013": {nombre: "APARICIO  GUTIERREZ ", ci: "8107124", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-014": {nombre: "ANGEL  OLIVERA ", ci: "5269147", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-015": {nombre: "MARCELINA  OLIVERA ", ci: "12730873", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-016": {nombre: "BERNARDO  GUTIERREZ ", ci: "8068661", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-017": {nombre: "MARINA  GUTIERREZ POMA", ci: "7809817", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-018": {nombre: "CARMEN DANIELA MERCADO ", ci: "8971899", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-019": {nombre: "MARCO  CONDORI HUARACHI", ci: "1946164", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-020": {nombre: "WALTER GUTIERREZ RELUZ", ci: "11374006", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-021": {nombre: "FRANCISCO RELUZ VALENCIA", ci: "8174939", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-022": {nombre: "GUADALUPE  RELUZ DE HINOJOSA ", ci: "8106586", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-023": {nombre: "TOMAS OLIVERA MONTAÑO", ci: "7674040", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-024": {nombre: "GREGORIO  SEJAS ROCHA", ci: "9661587", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-025": {nombre: "FRANCISCO  GUIZADA LOZA", ci: "4672920", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-026": {nombre: "DELIO CHOQUE  LUNA", ci: "1854795", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-027": {nombre: "ISABEL  SEJAS OLIVERA", ci: "11365972", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-028": {nombre: "JAIME FERNANDEZ TAPIA", ci: "8222565", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-029": {nombre: "IGNACIO MAMANI RODRIGUEZ", ci: "", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-030": {nombre: "LUZ ADELA COCA CABRERA", ci: "7667876", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-031": {nombre: "JULIAN OLIVERA APAZA", ci: "2919441", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-032": {nombre: "EXALTACIÓN GARCIA VASQUEZ", ci: "3943724", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-033": {nombre: "JOSÉ LUIS SEJAS VASQUEZ", ci: "7803694", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-034": {nombre: "EMIGDIO SEJAS RODRIGUEZ", ci: "4772874", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-035": {nombre: "GERMAN TENORIO COLICHO", ci: "2955294", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-036": {nombre: "ALEX GABRIEL MENDOZA TERCEROS", ci: "12478451", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-037": {nombre: "BRAULIO MANDOZA TERCEROS", ci: "9823728", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-038": {nombre: "JUANITO MENDOZA YUCRA", ci: "8911525", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-039": {nombre: "ESTELA FRANCO LÓPEZ", ci: "8957057", Asociación: "CARMEN SURUTU", estado: "Afiliado válido"},
"BV-D6-040": {nombre: "ALEJANDRO SULLCA QUIÑONES", ci: "3948869", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-041": {nombre: "ENRIQUETA MORALES MAITA", ci: "7691294", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-042": {nombre: "JUAN  SULLCA ACUÑA", ci: "3950187", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-043": {nombre: "WALBERTO SULLCA LABAYEN", ci: "14593121", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-044": {nombre: "ALFREDO PARDO RIOS", ci: "7690974", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-045": {nombre: "LUCAS JUCUMARI POMA", ci: "6224212", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-046": {nombre: "CESILIO ROMERO VILA", ci: "6335510", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-047": {nombre: "BISMAR  IRAÑA  PASTOR", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-048": {nombre: "SERAPIO SULLCA ", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-049": {nombre: "PEDRO  CONDORI ", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-050": {nombre: "WILBER IRAÑA  PASTOR", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-051": {nombre: "JULIAN OLIVERA ", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-052": {nombre: "ANGEL  OLIVERA ", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-053": {nombre: "MACARIO MESA ", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-054": {nombre: "VICENTA ALBA ", ci: "", Asociación: "SAN JUAN DE SAGUAYO", estado: "Afiliado válido"},
"BV-D6-055": {nombre: "ELENA  QUIROS DE RELUZ ", ci: "6272379", Asociación: "SAN JORGE", estado: "Afiliado válido"},
"BV-D6-056": {nombre: "SIMÓN GUIZADA CARTAGENA", ci: "8120477", Asociación: "SAN JORGE", estado: "Afiliado válido"},
"BV-D6-057": {nombre: "PAULINA HUAINOCA SALAZAR", ci: "6240041", Asociación: "SAN JORGE", estado: "Afiliado válido"},
"BV-D6-058": {nombre: "EUGENIO RELUZ ALMANZA", ci: "6325073", Asociación: "SAN JORGE", estado: "Afiliado válido"},
"BV-D6-059": {nombre: "AURELIA SANIZO QUISPE", ci: "5311021", Asociación: "SAN JORGE", estado: "Afiliado válido"},
"BV-D6-060": {nombre: "EDUARDO RELUZ VALENCIA", ci: "6240042", Asociación: "SAN JORGE", estado: "Afiliado válido"},
"BV-D6-061": {nombre: "SANTOS LORA MOSCOSO", ci: "9004090", Asociación: "SAN JUAN SURUTÚ", estado: "Afiliado válido"},
"BV-D6-062": {nombre: "LIDIA  LOPEZ PAREDES", ci: "7749157", Asociación: "SAN JUAN SURUTÚ", estado: "Afiliado válido"},
"BV-D6-063": {nombre: "ARMIN JALDIN  CLAROS", ci: "6396730", Asociación: "SAN JUAN SURUTÚ", estado: "Afiliado válido"},
"BV-D6-064": {nombre: "CANDELARIA SOSA VACA", ci: "3191881", Asociación: "SAN JUAN SURUTÚ", estado: "Afiliado válido"},
"BV-D6-065": {nombre: "RENAN YLLESCAS GONZALES", ci: "1886715", Asociación: "SAN JUAN SURUTÚ", estado: "Afiliado válido"},
"BV-D6-066": {nombre: "MANUELA CUELLAR BAZÁN", ci: "4171784", Asociación: "SAN JUAN SURUTÚ", estado: "Afiliado válido"},
"BV-D6-067": {nombre: "MATILDE YUCRA QUISPE", ci: "5897679", Asociación: "SAN JUAN SURUTÚ", estado: "Afiliado válido"},

};

